swagger: '2.0'
info:
  title: TaskTrigger API
  description: 'API for TaskTrigger web app, built during the Cloud and Big Data course at Columbia University.'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /discover:
    get:
      summary: The endpoint for searching events.
      description: |
        This API takes in one meassage from client and return a list of events
      tags:
        - discover
      operationId: searchEvent
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/DiscoverRequest'
      responses:
        '200':
          description: A Discover response
          schema:
            $ref: '#/definitions/DiscoverResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /create_event:
    post:
      summary: The endpoint for creating events.
      description: |
        This API takes in one meassage from client and add this event to the database.
      tags:
        - create_event
      operationId: createEvent
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateEventRequest'
      responses:
        '200':
          description: A create_event response
          schema:
            $ref: '#/definitions/CreateEventResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /create_event/get_advice:
    get:
      summary: The endpoint for getting event timeslot recommendation.
      description: |
        This API takes in one meassage from client and return recommendation on timeslot for an event.
      tags:
        - create_event
      operationId: get_event_advice
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/DiscoverRequest'
      responses:
        '200':
          description: A create_event/get_advice response
          schema:
            $ref: '#/definitions/DiscoverResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Event:
    type: object
    properties:
      event_id:
        type: integer
      creator_id:
        type: integer
      event_name:
        type: string
      start_date_time:
        type: string
        format: datetime
      end_date_time:
        type: string
        format: datetime
      location:
        type: string
      coordinate:
        type: string
      description:
        type: string
      visibility:
        type: integer
      create_time:
        type: string
        format: datetime
      capacity:
        type: integer


  DiscoverRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/DiscoverRequestMessage'

  DiscoverResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/DiscoverResponseMessage'


  DiscoverRequestMessage:
    type: object
    properties:
      user_id:
        type: integer
      visibility:
        type: integer
      event_time:
        type: string
        format: datetime
      event_location:
        type: string
      event_name:
        type: string

  DiscoverResponseMessage:
    type: object
    properties:
      user_id:
        type: integer
      events:
        type: array
        items:
          $ref: '#/definitions/Event'

  CreateEventRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/CreateEventRequestMessage'

  CreateEventResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/CreateEventResponseMessage'

  CreateEventRequestMessage:
    type: object
    properties:
      event:
        $ref: '#/definitions/Event'
      participants_id:
        type: array
        items: integer

  CreateEventResponseMessage:
    type: object
    properties:
      user_id:
        type: integer
      event_id:
        type: integer
      success:
        type: integer



  GeneralRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  GeneralResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  Message:
    type: object
    properties:
      type:
        type: string
      unstructured:
        $ref: '#/definitions/UnstructuredMessage'
  UnstructuredMessage:
    type: object
    properties:
      id:
        type: string
      text:
        type: string
      timestamp:
        type: string
        format: datetime
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
